apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumidor-inclusao-worker
  labels:
    app: consumidor-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumidor-worker
  template:
    metadata:
      labels:
        app: consumidor-worker
    spec:
      containers:
      - name: consumidor-inclusao-worker
        image: fiaptechchallenge.azurecr.io/contatos.consumidor.inclusao.worker
        envFrom:
          - configMapRef:
             name: configmap-worker